sudo: false
language: generic

branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
    - env: ENV=vimlint
    - env: ENV=test_nvim
    - env: ENV=test_vim
    - env: ENV=vint
      language: python

install:
  - |
    if [ "$ENV" = "test_nvim" ]; then
      eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"
    fi

script: make $ENV
